[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
goerli = { key = "{$ETHERSCAN_API_KEY}" }
arbitrum-goerli = { key = "{$ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }
arbitrum = { key = "{$ARBITRUM_ETHERSCAN_API_KEY}", url="https://api.arbiscan.io/api" }
bnb-chain = {key = "{BSC_SCAN_API_KEY}", url="https://api.bscscan.com/api" }
bnb-chain-testnet = {key = "{BSC_SCAN_API_KEY}", url="https://api-testnet.bscscan.com/api" }