[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
goerli = { key = "{$ETHERSCAN_API_KEY}" }
arbitrum-goerli = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_API_KEY}" }
